name: Build Android APK
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install System Dependencies and AIDL
      run: |
        sudo apt-get update
        sudo apt-get install -y git zip unzip autoconf libtool pkg-config zlib1g-dev \
          libncurses5-dev libncursesw5-dev libreadline-dev libsqlite3-dev libgdbm-dev \
          libssl-dev libffi-dev liblzma-dev build-essential android-sdk-build-tools

        
        sudo cp $(which aidl) /usr/local/bin/aidl || true
        sudo chmod +x /usr/local/bin/aidl

        pip install --upgrade pip setuptools wheel
        pip install "buildozer==1.5.0" "cython<3.0" virtualenv

    - name: Prepare Buildozer AIDL Folder
      run: |
        mkdir -p ~/.buildozer/android/platform/android-sdk/build-tools/33.0.0/
        cp /usr/local/bin/aidl ~/.buildozer/android/platform/android-sdk/build-tools/33.0.0/aidl || true

    - name: Build with Buildozer
      run: |
        buildozer -v android debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: Capuchinator-APK
        path: bin/*.apk
